name: "GRDB CI"

on:
  push:
    branches: 
      - master
      - development
    paths:
      - 'GRDB/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Makefile'
      - 'Package.swift'
  pull_request:
    paths:
      - 'GRDB/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Makefile'
      - 'Package.swift'

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  macOS:
    name: macOS
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.1, Swift 5.7.1"
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7.0"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project GRDB.xcodeproj -scheme GRDB -destination "platform=macOS" OTHER_SWIFT_FLAGS='$(inherited) -D SQLITE_ENABLE_FTS5 -D SQLITE_ENABLE_PREUPDATE_HOOK' GCC_PREPROCESSOR_DEFINITIONS='$(inherited) GRDB_SQLITE_ENABLE_PREUPDATE_HOOK=1' clean test
  iOS:
    name: iOS
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            shell: "/bin/zsh {0}"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: make test_framework_GRDBiOS_maxTarget_maxSwift
  SPM:
    name: SPM
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            shell: "/bin/zsh {0}"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: make test_SPM test_install_SPM
  SQLCipher3:
    name: SQLCipher3
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            shell: "/bin/zsh {0}"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: make test_framework_SQLCipher3Encrypted
  SQLCipher4:
    name: SQLCipher4
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            shell: "/bin/zsh {0}"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: make test_framework_SQLCipher4Encrypted
  CustomSQLite:
    name: CustomSQLite
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            shell: "/bin/zsh {0}"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: make test_framework_GRDBCustomSQLiteOSX
  XCFramework:
    name: XCFramework
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_14.0.1.app"
            runsOn: macOS-12
            name: "macOS 12, Xcode 14.0.1, Swift 5.7"
            shell: "/bin/zsh {0}"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: make test_archive_GRDBOSX_xcframework
    